### ISSUE TITLE
Building in Azure Pipeline (Android resource linking failed)

### ISSUE THREAD

**Issue by pieteckhart** [nightscout/AndroidAPS#277]
Hi,

I'm trying to help out my brother in law with building an APK because he was having troubles building it himself.
3 months ago we managed to build one on his PC but now he can't get it to work.

Today I've tried solving his problems by configuring an build pipeline in Azure Devops.
I'm a .Net programmer so I am used to work with Microsoft's products so this would be an easy way to automate this build.
I also have some experience building native Android apps using Xamarin.

Can someone please help me with any of the following?
When I get this working I would gladly share my build pipeline yaml script and instructions so others can also setup a pipeline for themselves.

Thanks!

(I'm trying to build the latest version 2.8.2)

1. In order to get a build working I needed to upgrade ndkVersion from 21.1.6352462 to 21.3.6528147 because the build agent was based on an image that did not have this specific version. Can this cause problems?
**UPDATE:** It seems that i can use `sdkmanager --install "21.1.6352462"` as a build step to install other ndks. After I have a successful release build I will look into this next. My endgoal is to have a single yaml script to build the app without needing to modify anything in the code.

2. I can successfully build (and sign) debug APKs but when I build a release version it fails during the linking process:
```
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:24: AAPT: error: resource color/importListFileName (aka info.nightscout.androidaps.core:color/importListFileName) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:34: AAPT: error: resource color/importListFileName (aka info.nightscout.androidaps.core:color/importListFileName) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:57: AAPT: error: resource color/importListFileName (aka info.nightscout.androidaps.core:color/importListFileName) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:84: AAPT: error: resource color/importListAdditionalInfo (aka info.nightscout.androidaps.core:color/importListAdditionalInfo) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:95: AAPT: error: resource color/importListAdditionalInfo (aka info.nightscout.androidaps.core:color/importListAdditionalInfo) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:116: AAPT: error: resource color/importListAdditionalInfo (aka info.nightscout.androidaps.core:color/importListAdditionalInfo) not found.
         
     /Users/runner/work/1/s/core/src/main/res/layout/maintenance_import_list_item.xml:127: AAPT: error: resource color/importListAdditionalInfo (aka info.nightscout.androidaps.core:color/importListAdditionalInfo) not found.
```
I've checked and found two colors.xml files:
- app\src\main\res\values\colors.xml (seems ok)
- core\src\main\res\values\colors.xml (not containing importListFileName/importListAdditionalInfo)

I've tried to add the seemingly missing colors to the core colors.xml and this results in other build errors:
```
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/runner/work/1/s/medtronic/src/main/res/layout/medtronic_fragment.xml:500: AAPT: error: resource string/combo_refresh (aka info.nightscout.androidaps.plugins.pump.medtronic:string/combo_refresh) not found.
         
     /Users/runner/work/1/s/rileylink/build/intermediates/packaged_res/release/layout/rileylink_status.xml:11: AAPT: error: resource style/AppTheme.AppBarOverlay (aka info.nightscout.androidaps.plugins.pump.medtronic:style/AppTheme.AppBarOverlay) not found.
         
     /Users/runner/work/1/s/rileylink/build/intermediates/packaged_res/release/layout/rileylink_status.xml:34: AAPT: error: resource drawable/ic_refresh (aka info.nightscout.androidaps.plugins.pump.medtronic:drawable/ic_refresh) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:10: AAPT: error: resource string/sixdigitnumber (aka info.nightscout.androidaps.plugins.pump.medtronic:string/sixdigitnumber) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:21: AAPT: error: resource array/medtronicPumpTypeArray (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicPumpTypeArray) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:29: AAPT: error: resource array/medtronicPumpFreqArray (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicPumpFreqArray) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:29: AAPT: error: resource array/medtronicPumpFreqValues (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicPumpFreqValues) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:61: AAPT: error: resource array/medtronicBolusDelay (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicBolusDelay) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:69: AAPT: error: resource array/medtronicEncoding (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicEncoding) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:69: AAPT: error: resource array/medtronicEncodingValues (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicEncodingValues) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:77: AAPT: error: resource array/medtronicBatteryType (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicBatteryType) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:77: AAPT: error: resource array/medtronicBatteryTypeValues (aka info.nightscout.androidaps.plugins.pump.medtronic:array/medtronicBatteryTypeValues) not found.
         
     /Users/runner/work/1/s/medtronic/src/main/res/xml/pref_medtronic.xml:85: AAPT: error: resource array/onOff (aka info.nightscout.androidaps.plugins.pump.medtronic:array/onOff) not found.
```
3. Also when running a debug version it looks weird and doesn't seem to work correctly
**UPDATE: solved! I was installing the wear apk on my device.**

**Comment by rICTx-T1D** [comment]
Maybe you build and deploy the WearOS-image on smartphone...

**Comment by pieteckhart** [comment]
> Maybe you build and deploy the WearOS-image on smartphone...

I just woke up and realized that it indeed must be the android wear interface :)
Glad to see someone already came to the same conclusion, only six hours before me. I should have gone to bed earlier ;)

I will ty to build the correct apk and will report back if this solves my other problem.

Thanks!

**Comment by pieteckhart** [comment]
Ok. I just tried and found out I was building everything correctly (debug mode still) but was copying over the resulting apk when publishing. The following yaml script now builds a debug version:

```
trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
    
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksign: true
    apksignerKeystoreFile: 'keystore.jks'
    apksignerKeystorePassword: '********'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: '*********'
    zipalign: false

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/full/debug/'
    artifactName: 'apks'
    publishLocation: 'container'
```
